name: quran
description: "Quran"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  sqflite: ^2.4.2
  provider: ^6.1.5+1
  path: ^1.9.1
  salomon_bottom_bar: ^3.3.2
  hive_ce: ^2.19.3
  path_provider: ^2.1.5
  wakelock_plus: ^1.5.1
  flutter_material_color_picker: ^1.2.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.2
  pasteboard: ^0.5.0
  arabic_justified_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/fonts/
    - assets/fontpages/

  fonts:
    - family: 'Gilroy'
      fonts:
        - asset: assets/fonts/gilroy_regular.ttf
    - family: 'Gilroy Medium'
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: 'Uthmanic Hafs'
      fonts:
        - asset: assets/fonts/uthmanic_hafs_v_22.ttf
    - family: 'SP Pro'
      fonts:
        - asset: assets/fonts/sf_pro_regular.ttf
    - family: 'Surah name'
      fonts:
        - asset: assets/fonts/surah_name_v2.ttf